// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjidsifrdmaxubkmqung.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqaWRzaWZyZG1heHVia21xdW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODk0MzMsImV4cCI6MjA2NjI2NTQzM30.tehK7_DavEkBmfQPxB29wVOiu8HlXLZnz97ZLkVRRfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);